// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMGq_rqQL0aYDu9c07xGMHEk511Ih9eM',
    appId: '1:903256679072:web:8df430793d6b727ba65fc5',
    messagingSenderId: '903256679072',
    projectId: 'flutter-app-academia',
    authDomain: 'flutter-app-academia.firebaseapp.com',
    storageBucket: 'flutter-app-academia.appspot.com',
    measurementId: 'G-ZGSPJMH2Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOwqZIakXQZ0kl97KXH5eOfDAI8eMQ68',
    appId: '1:903256679072:android:d92ea5c2f2499da8a65fc5',
    messagingSenderId: '903256679072',
    projectId: 'flutter-app-academia',
    storageBucket: 'flutter-app-academia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcbp4yQ28vZwsteWUxq9M8pMgA_yt_DTE',
    appId: '1:903256679072:ios:0e1ac55900c4c328a65fc5',
    messagingSenderId: '903256679072',
    projectId: 'flutter-app-academia',
    storageBucket: 'flutter-app-academia.appspot.com',
    iosBundleId: 'com.example.projetoAppAcademia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcbp4yQ28vZwsteWUxq9M8pMgA_yt_DTE',
    appId: '1:903256679072:ios:43ff46266299b37ea65fc5',
    messagingSenderId: '903256679072',
    projectId: 'flutter-app-academia',
    storageBucket: 'flutter-app-academia.appspot.com',
    iosBundleId: 'com.example.projetoAppAcademia.RunnerTests',
  );
}
